package models

// EntityModel is a base entity model that can be inherited from and continue to use for other models
type EntityModel struct {
	ID        string  `bson:"_id"`       // ID generated by the database. For different databases and their drivers this implemtnation may differ
	CreatedAt string  `bson:"createdAt"` // date and time in UTC matching ISO 8601 format for when the entity was created
	UpdatedAt *string `bson:"updatedat"` // date and time in UTC formatted as ISO 8601 when the record was modified
	CreatedBy string  `bson:"createdBy"` // User ID, email, number, etc. identifier that created the entity
	UpdatedBy *string `bson:"updatedBy"` // User ID, email, number, etc. identifier that updated the entity
}
